name: Testing the program
on: push

jobs:
  check_repo:
    name: "Check if the repo is clean"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check_repo
        run: |
          BAD_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
          for FILES in $BAD_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [ "$BAD_FILES" != ""]; then
            exit 1
          fi

  testing:
    name: "Testing the program"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: |
          cpp --version
          cmake .
          make
        timeout-minutes: 2
