name: Testing the program
on: push

jobs:
  check_repo:
    name: "Check if the repo is clean"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check_repo
        run: |
          BAD_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
          for FILES in $BAD_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [ "$BAD_FILES" != ""]; then
            exit 1
          fi

  testing:
    name: "Testing the program and codeql"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run tests
        run: |
          sudo dnf install -y libconfig-devel
          cmake .
          make
        timeout-minutes: 5

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
